print('Nama: Arrafi Randyansyah Faizi')
print('Fakultas: FMIPA (jurusan: Kimia')
print('Universitas: ITB')
print('Alasan ingin masuk GDSC: Tadinya karena FOMO,')
print('tapi saya mencoba ngeksplor ternyata seru juga.')
print('Sekarang tujuan saya masuk GDSC untuk bisa ahli dibidang Kimia Komputasi')