# -*- coding: utf-8 -*-
"""kode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-N48FrZSgECJQCUrWuRZCafFdxHG8YD
"""

print("Nama: Gishelawati")
print("Jurusan: Astronomi")
print("Universitas: ITB")
print("Alasan ingin masuk GDSC: Ingin belajar lebih tentang pemrograman")